export const dinosaurSpecies = {
    allosaurus: {
        name: "Allosaurus",
        description: "Top predator of the Late Jurassic, fast and agile with serrated teeth",
        color: "bg-amber-600",
        size: "Medium-Large",
        diet: "Carnivore",
        specialAbility: "Pack hunting",
        baseStats: {
            hunting: 8,
            speed: 7,
            strength: 7,
            stamina: 6,
            senses: 7
        },
        growthRates: {
            health: 1.2,
            energy: 1.0,
            hunger: 1.3
        },
        preyTypes: ["small", "medium", "large"],
        threats: ["allosaurus", "sauropod", "stegosaurus"],
        facts: [
            "Allosaurus was one of the top predators of the Late Jurassic period, living about 155 to 145 million years ago.",
            "An adult Allosaurus could grow up to 28 feet (8.5 meters) long and weigh over 2 tons.",
            "Allosaurus had about 70-80 sharp, serrated teeth designed for slicing through flesh.",
            "Scientists believe Allosaurus could run at speeds of up to 20-30 mph (30-45 km/h).",
            "Allosaurus had three clawed fingers on each hand, which it used to grab and hold prey.",
            "Fossil evidence suggests Allosaurus sometimes hunted in groups to take down larger dinosaurs.",
            "Allosaurus had relatively short but powerful arms compared to its body size.",
            "The name 'Allosaurus' means 'different lizard,' referring to its unusual vertebrae.",
            "Allosaurus fossils have been found primarily in the western United States, particularly in Colorado, Utah, and Wyoming.",
            "An Allosaurus had a life expectancy of about 20-25 years in the wild."
        ]
    },
    dilophosaurus: {
        name: "Dilophosaurus",
        description: "Early Jurassic predator with distinctive cranial crests",
        color: "bg-green-600",
        size: "Medium",
        diet: "Carnivore",
        specialAbility: "Speed burst",
        baseStats: {
            hunting: 6,
            speed: 9,
            strength: 5,
            stamina: 7,
            senses: 6
        },
        growthRates: {
            health: 0.9,
            energy: 1.3,
            hunger: 1.1
        },
        preyTypes: ["small", "medium"],
        threats: ["allosaurus", "ceratosaurus"],
        facts: [
            "Dilophosaurus lived during the Early Jurassic period, about 193 million years ago.",
            "It was characterized by a pair of rounded crests on its skull, which may have been used for display or species recognition.",
            "Unlike its depiction in popular media, there is no evidence that Dilophosaurus could spit venom or had a neck frill.",
            "Dilophosaurus was about 20 feet (6 meters) long and weighed approximately 1,000 pounds (450 kg).",
            "Its jaws were relatively weak compared to later theropods, suggesting it may have hunted small prey or scavenged.",
            "Dilophosaurus had long, strong legs and was likely one of the fastest dinosaurs of its time.",
            "The name 'Dilophosaurus' means 'two-crested lizard,' referring to its distinctive head ornaments.",
            "Fossil evidence suggests Dilophosaurus may have lived near water sources and hunted fish.",
            "It had five fingers on each hand, unlike later theropods which had fewer digits.",
            "Dilophosaurus fossils have primarily been found in Arizona in the United States."
        ]
    },
    ceratosaurus: {
        name: "Ceratosaurus",
        description: "Theropod with distinctive horns and plates",
        color: "bg-red-800",
        size: "Medium-Large",
        diet: "Carnivore",
        specialAbility: "Aquatic hunting",
        baseStats: {
            hunting: 7,
            speed: 6,
            strength: 8,
            stamina: 6,
            senses: 6
        },
        growthRates: {
            health: 1.1,
            energy: 0.9,
            hunger: 1.2
        },
        preyTypes: ["small", "medium", "aquatic"],
        threats: ["allosaurus", "large"],
        facts: [
            "Ceratosaurus lived during the Late Jurassic period, about 150 million years ago.",
            "It had a distinctive horn on its snout and smaller horns over each eye, likely used for display.",
            "Ceratosaurus had a row of small osteoderms (bony plates) along its back.",
            "It was about 20 feet (6 meters) long and weighed around 1 ton.",
            "Unlike many other theropods, Ceratosaurus had four fingers on each hand instead of three.",
            "Some paleontologists believe Ceratosaurus may have been semi-aquatic, hunting fish and other water animals.",
            "Ceratosaurus had an unusually large head compared to its body size.",
            "Fossils have been found in North America, Europe, and Tanzania.",
            "The name 'Ceratosaurus' means 'horned lizard' referring to its nasal horn.",
            "It likely competed with other predators like Allosaurus for food resources."
        ]
    },
    stegosaurus: {
        name: "Stegosaurus",
        description: "Heavily armored herbivore with distinctive back plates",
        color: "bg-amber-800",
        size: "Large",
        diet: "Herbivore",
        specialAbility: "Tail defense",
        baseStats: {
            hunting: 0,
            speed: 4,
            strength: 8,
            stamina: 9,
            senses: 3
        },
        growthRates: {
            health: 1.5,
            energy: 0.8,
            hunger: 0.9
        },
        preyTypes: ["plants"],
        threats: ["allosaurus", "ceratosaurus"],
        facts: [
            "Stegosaurus lived during the Late Jurassic period, about 155 to 145 million years ago.",
            "It had 17 large bony plates arranged in two alternating rows along its back and tail.",
            "The plates may have been used for display, species recognition, or thermoregulation rather than defense.",
            "Stegosaurus had a spiked tail called a thagomizer, which was its primary defensive weapon.",
            "Despite its massive size (up to 30 feet long), Stegosaurus had a brain the size of a dog's.",
            "It was a herbivore that likely fed on low-growing vegetation such as ferns and bushes.",
            "Stegosaurus had short forelimbs and longer hind limbs, giving it a distinctive posture.",
            "The name 'Stegosaurus' means 'roof lizard,' referring to its plates.",
            "It was one of the least intelligent dinosaurs relative to its body size.",
            "Stegosaurus fossils have been found in western North America and Portugal."
        ]
    }
};

// Creature Types with Stats
export const creatureTypes = {
    mothersaur: {
        name: "Mother Allosaurus",
        description: "Your protective mother, teaching you survival skills.",
        size: 3,
        fierceness: 90,
        agility: 70,
        energy: 100,
        nutrition: 0,
        minGrowthToHunt: 99, // Cannot be hunted
        maxGrowthToHide: 0, // Cannot be hidden from
        dangerLevel: 0, // Not dangerous to player
        category: "large",
        habitat: ["plains", "forest"],
        facts: ["Female Allosaurus likely protected their young for some time after hatching.",
            "An adult Allosaurus could reach lengths of 8-12 meters and weigh up to 2 tons.",
            "Allosaurus mothers may have brought food back to their young or led them to carcasses."]
    },
    dryosaurus: {
        name: "Dryosaurus",
        description: "Small, agile plant-eater that moves in small herds.",
        size: 1,
        fierceness: 20,
        agility: 80,
        energy: 50,
        nutrition: 30,
        minGrowthToHunt: 2,
        maxGrowthToHide: 0,
        dangerLevel: 1,
        category: "small",
        habitat: ["plains", "forest", "grassland"],
        facts: ["Dryosaurus was a small, fast-running herbivore about 3 meters long.",
            "They likely lived in small herds for protection against predators.",
            "Dryosaurus had a horny beak and cheek teeth for processing plant material.",
            "Their name means 'oak lizard' because they likely lived in forested areas."]
    },
    ornitholestes: {
        name: "Ornitholestes",
        description: "Small predator hunting insects and small vertebrates.",
        size: 1,
        fierceness: 40,
        agility: 90,
        energy: 40,
        nutrition: 20,
        minGrowthToHunt: 2,
        maxGrowthToHide: 1,
        dangerLevel: 1,
        category: "small",
        habitat: ["forest", "marsh", "grassland"],
        facts: ["Ornitholestes was a small carnivorous dinosaur about 2 meters long.",
            "It had a lightweight skull with sharp teeth for catching small prey.",
            "Unlike how it's sometimes depicted, it probably didn't have a crest on its nose.",
            "It likely hunted small animals including lizards, mammals, and juvenile dinosaurs."]
    },
    stegosaurus: {
        name: "Stegosaurus",
        description: "Large herbivore with plates on its back and a spiked tail.",
        size: 3,
        fierceness: 60,
        agility: 30,
        energy: 90,
        nutrition: 80,
        minGrowthToHunt: 4,
        maxGrowthToHide: 1,
        dangerLevel: 3,
        category: "large",
        habitat: ["plains", "grassland"],
        facts: ["Stegosaurus had 17 bony plates along its back and four spikes on its tail called a thagomizer.",
            "Despite its size, its brain was only about the size of a walnut.",
            "The plates may have been used for display, species recognition, or temperature regulation.",
            "A full-grown Stegosaurus could reach 9 meters in length."]
    },
    diplodocus: {
        name: "Diplodocus",
        description: "Enormous long-necked herbivore that moves in herds.",
        size: 4,
        fierceness: 50,
        agility: 20,
        energy: 100,
        nutrition: 90,
        minGrowthToHunt: 99, // Cannot be hunted
        maxGrowthToHide: 1,
        dangerLevel: 4, // Can cause crushing injuries
        category: "sauropod",
        habitat: ["plains"],
        facts: ["Diplodocus was one of the longest dinosaurs, reaching lengths of up to 27 meters.",
            "Despite its enormous size, it would have weighed less than modern elephants.",
            "It had a very long whip-like tail that may have been used for defense.",
            "Diplodocus likely traveled in herds for protection against predators like Allosaurus."]
    },
    allosaurus: {
        name: "Allosaurus",
        description: "Large predator and your main competitor.",
        size: 3,
        fierceness: 95,
        agility: 60,
        energy: 90,
        nutrition: 70,
        minGrowthToHunt: 4,
        maxGrowthToHide: 2,
        dangerLevel: 5, // Very dangerous
        category: "large",
        habitat: ["plains", "forest", "grassland"],
        facts: ["Allosaurus was the dominant predator of the Late Jurassic period.",
            "It had serrated, blade-like teeth designed for slicing through flesh.",
            "An adult Allosaurus could exert an estimated bite force of 805 to 2,148 N.",
            "Its name means 'different lizard' referring to its unusual vertebrae."]
    },
    ceratosaurus: {
        name: "Ceratosaurus",
        description: "Predator with a distinctive horn on its nose.",
        size: 3,
        fierceness: 85,
        agility: 55,
        energy: 85,
        nutrition: 65,
        minGrowthToHunt: 4,
        maxGrowthToHide: 2,
        dangerLevel: 4,
        category: "large",
        habitat: ["riverbank", "marsh", "lake"],
        facts: ["Ceratosaurus had a prominent horn on its snout and smaller horns above its eyes.",
            "Unlike many theropods, it had four fingers on each hand instead of three.",
            "Some evidence suggests it may have been semi-aquatic, hunting in and around water.",
            "Ceratosaurus lived alongside Allosaurus but occupied a different ecological niche."]
    },
    brachiosaurus: {
        name: "Brachiosaurus",
        description: "Massive sauropod with an upright posture.",
        size: 5,
        fierceness: 40,
        agility: 10,
        energy: 100,
        nutrition: 100,
        minGrowthToHunt: 99, // Cannot be hunted
        maxGrowthToHide: 1,
        dangerLevel: 4, // Dangerous due to size
        category: "sauropod",
        habitat: ["plains", "forest"],
        facts: ["Brachiosaurus could reach heights of around 13 meters (43 feet).",
            "Its name means 'arm lizard' because its front legs were longer than its back legs.",
            "It held its neck more upright than other sauropods, allowing it to browse high vegetation.",
            "An adult Brachiosaurus may have weighed up to 50 tons."]
    },
    centipede: {
        name: "Giant Centipede",
        description: "Arthropod hiding in the underbrush.",
        size: 0,
        fierceness: 5,
        agility: 60,
        energy: 10,
        nutrition: 5,
        minGrowthToHunt: 1,
        maxGrowthToHide: 4,
        dangerLevel: 0,
        category: "tiny",
        habitat: ["forest", "marsh"],
        facts: ["Jurassic centipedes were similar to modern ones but could grow much larger.",
            "They were arthropods with many body segments and a pair of legs on each segment.",
            "Centipedes were predators, hunting smaller invertebrates.",
            "They likely lived in moist, sheltered environments like forest floors and under logs."]
    },
    dragonfly: {
        name: "Giant Dragonfly",
        description: "Fast-flying insect near water sources.",
        size: 0,
        fierceness: 2,
        agility: 95,
        energy: 5,
        nutrition: 3,
        minGrowthToHunt: 1,
        maxGrowthToHide: 4,
        dangerLevel: 0,
        category: "tiny",
        habitat: ["riverbank", "marsh", "lake"],
        facts: ["Jurassic dragonflies resembled their modern relatives but could be much larger.",
            "They were skilled aerial predators, catching other insects in flight.",
            "Dragonflies have existed for over 300 million years, predating dinosaurs.",
            "They spent their larval stage in water, making them common near rivers and marshes."]
    },
    lizard: {
        name: "Primitive Lizard",
        description: "Small reptile scurrying through the underbrush.",
        size: 0,
        fierceness: 10,
        agility: 85,
        energy: 15,
        nutrition: 10,
        minGrowthToHunt: 1,
        maxGrowthToHide: 3,
        dangerLevel: 0,
        category: "tiny",
        habitat: ["forest", "marsh", "grassland", "rocky"],
        facts: ["Small lizards were already widespread by the Jurassic period.",
            "They likely fed on insects and other small invertebrates.",
            "These early lizards were distant relatives of modern species.",
            "They would have been common prey for small dinosaurs and other predators."]
    },
    pterosaur: {
        name: "Pterosaur",
        description: "Flying reptile that is difficult to catch.",
        size: 1,
        fierceness: 25,
        agility: 100,
        energy: 40,
        nutrition: 25,
        minGrowthToHunt: 3,
        maxGrowthToHide: 1,
        dangerLevel: 1,
        category: "small",
        habitat: ["cliff", "lake", "plains"],
        facts: ["Pterosaurs were flying reptiles, not dinosaurs, but lived alongside them.",
            "They had hollow bones and wing membranes stretched between their elongated fourth fingers and bodies.",
            "Their diet varied by species but included fish, insects, and small land animals.",
            "Pterosaurs were the first vertebrates to evolve powered flight."]
    },
    dino_eggs: {
        name: "Dinosaur Eggs",
        description: "Unguarded eggs that provide easy nutrition.",
        size: 0,
        fierceness: 0,
        agility: 0,
        energy: 5,
        nutrition: 15,
        minGrowthToHunt: 1,
        maxGrowthToHide: 4,
        dangerLevel: 0,
        category: "tiny",
        habitat: ["plains", "forest", "grassland", "cliff"],
        facts: ["Many dinosaur species laid eggs, often in ground nests.",
            "Unguarded nests were vulnerable to predators looking for an easy meal.",
            "Egg predation likely led to the evolution of parental care in some dinosaur species.",
            "Allosaurus and other predators would have readily fed on eggs when they found them."]
    },
    mammal: {
        name: "Primitive Mammal",
        description: "Small furry creature active at night.",
        size: 0,
        fierceness: 15,
        agility: 90,
        energy: 20,
        nutrition: 12,
        minGrowthToHunt: 1,
        maxGrowthToHide: 3,
        dangerLevel: 0,
        category: "tiny",
        habitat: ["forest", "grassland"],
        facts: ["Mammals during the Jurassic were mostly small and nocturnal.",
            "Many early mammals resembled modern shrews or rats.",
            "They likely ate insects, plants, and occasionally small reptiles.",
            "These early mammals were the ancestors of all modern mammal species."]
    },
    compsognathus: {
        name: "Compsognathus",
        description: "Tiny, fast-moving predator.",
        size: 0,
        fierceness: 30,
        agility: 95,
        energy: 30,
        nutrition: 15,
        minGrowthToHunt: 2,
        maxGrowthToHide: 2,
        dangerLevel: 1,
        category: "small",
        habitat: ["plains", "forest", "grassland"],
        facts: ["Compsognathus was one of the smallest known dinosaurs, about the size of a chicken.",
            "It was a fast, agile predator that hunted small reptiles and mammals.",
            "Fossils show it had excellent eyesight for hunting.",
            "Its name means 'elegant jaw' referring to its delicate skull structure."]
    },
    fish: {
        name: "Jurassic Fish",
        description: "Aquatic prey animal found in water sources.",
        size: 0,
        fierceness: 5,
        agility: 90,
        energy: 20,
        nutrition: 15,
        minGrowthToHunt: 1,
        maxGrowthToHide: 3,
        dangerLevel: 0,
        category: "aquatic",
        habitat: ["riverbank", "lake"],
        facts: ["The Jurassic period had a diverse array of fish species.",
            "Many were similar to modern rays, sharks, and bony fish.",
            "They served as an important food source for semi-aquatic predators.",
            "Some grew to enormous sizes in the prehistoric oceans."]
    },
    crocodilian: {
        name: "Primitive Crocodilian",
        description: "Ambush predator lurking near water.",
        size: 2,
        fierceness: 70,
        agility: 40,
        energy: 60,
        nutrition: 40,
        minGrowthToHunt: 3,
        maxGrowthToHide: 1,
        dangerLevel: 3,
        category: "medium",
        habitat: ["riverbank", "marsh", "lake"],
        facts: ["Early crocodilians were more terrestrial than their modern descendants.",
            "They were important predators in aquatic and semi-aquatic environments.",
            "Some species could reach lengths of 3-4 meters.",
            "They used ambush tactics to catch prey coming to drink at water sources."]
    }
};